/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as InstalledRouteImport } from './routes/installed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicVisitRouteImport } from './routes/api/public/visit'
import { Route as ApiPublicMarkExtractedRouteImport } from './routes/api/public/mark-extracted'
import { Route as ApiPublicInstalledRouteImport } from './routes/api/public/installed'
import { Route as ApiPublicDownloadProgressRouteImport } from './routes/api/public/download-progress'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiMeStatsRouteImport } from './routes/api/me/stats'
import { Route as ApiMeLogoutRouteImport } from './routes/api/me/logout'
import { Route as ApiMeLoginRouteImport } from './routes/api/me/login'
import { Route as ApiAdminMarkNotificationReadRouteImport } from './routes/api/admin/mark-notification-read'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogNotificationRouteImport } from './routes/api/admin/log-notification'
import { Route as ApiAdminDeleteUserRouteImport } from './routes/api/admin/delete-user'
import { Route as ApiAdminDeleteSessionRouteImport } from './routes/api/admin/delete-session'
import { Route as ApiAdminDeleteNotificationRouteImport } from './routes/api/admin/delete-notification'
import { Route as ApiAdminDeleteDownloadRouteImport } from './routes/api/admin/delete-download'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminClearNotificationsRouteImport } from './routes/api/admin/clear-notifications'
import { Route as ApiAdminClearHistoryRouteImport } from './routes/api/admin/clear-history'
import { Route as ApiAdminClearDownloadsRouteImport } from './routes/api/admin/clear-downloads'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalledRoute = InstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVisitRoute = ApiPublicVisitRouteImport.update({
  id: '/api/public/visit',
  path: '/api/public/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarkExtractedRoute = ApiPublicMarkExtractedRouteImport.update({
  id: '/api/public/mark-extracted',
  path: '/api/public/mark-extracted',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstalledRoute = ApiPublicInstalledRouteImport.update({
  id: '/api/public/installed',
  path: '/api/public/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadProgressRoute =
  ApiPublicDownloadProgressRouteImport.update({
    id: '/api/public/download-progress',
    path: '/api/public/download-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeStatsRoute = ApiMeStatsRouteImport.update({
  id: '/api/me/stats',
  path: '/api/me/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeLogoutRoute = ApiMeLogoutRouteImport.update({
  id: '/api/me/logout',
  path: '/api/me/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeLoginRoute = ApiMeLoginRouteImport.update({
  id: '/api/me/login',
  path: '/api/me/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMarkNotificationReadRoute =
  ApiAdminMarkNotificationReadRouteImport.update({
    id: '/api/admin/mark-notification-read',
    path: '/api/admin/mark-notification-read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogNotificationRoute = ApiAdminLogNotificationRouteImport.update({
  id: '/api/admin/log-notification',
  path: '/api/admin/log-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteUserRoute = ApiAdminDeleteUserRouteImport.update({
  id: '/api/admin/delete-user',
  path: '/api/admin/delete-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteSessionRoute = ApiAdminDeleteSessionRouteImport.update({
  id: '/api/admin/delete-session',
  path: '/api/admin/delete-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteNotificationRoute =
  ApiAdminDeleteNotificationRouteImport.update({
    id: '/api/admin/delete-notification',
    path: '/api/admin/delete-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDeleteDownloadRoute = ApiAdminDeleteDownloadRouteImport.update({
  id: '/api/admin/delete-download',
  path: '/api/admin/delete-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClearNotificationsRoute =
  ApiAdminClearNotificationsRouteImport.update({
    id: '/api/admin/clear-notifications',
    path: '/api/admin/clear-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminClearHistoryRoute = ApiAdminClearHistoryRouteImport.update({
  id: '/api/admin/clear-history',
  path: '/api/admin/clear-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClearDownloadsRoute = ApiAdminClearDownloadsRouteImport.update({
  id: '/api/admin/clear-downloads',
  path: '/api/admin/clear-downloads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installed': typeof InstalledRoute
  '/me': typeof MeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/admin/clear-downloads': typeof ApiAdminClearDownloadsRoute
  '/api/admin/clear-history': typeof ApiAdminClearHistoryRoute
  '/api/admin/clear-notifications': typeof ApiAdminClearNotificationsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-download': typeof ApiAdminDeleteDownloadRoute
  '/api/admin/delete-notification': typeof ApiAdminDeleteNotificationRoute
  '/api/admin/delete-session': typeof ApiAdminDeleteSessionRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/log-notification': typeof ApiAdminLogNotificationRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/mark-notification-read': typeof ApiAdminMarkNotificationReadRoute
  '/api/me/login': typeof ApiMeLoginRoute
  '/api/me/logout': typeof ApiMeLogoutRoute
  '/api/me/stats': typeof ApiMeStatsRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/download-progress': typeof ApiPublicDownloadProgressRoute
  '/api/public/installed': typeof ApiPublicInstalledRoute
  '/api/public/mark-extracted': typeof ApiPublicMarkExtractedRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/installed': typeof InstalledRoute
  '/me': typeof MeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/admin/clear-downloads': typeof ApiAdminClearDownloadsRoute
  '/api/admin/clear-history': typeof ApiAdminClearHistoryRoute
  '/api/admin/clear-notifications': typeof ApiAdminClearNotificationsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-download': typeof ApiAdminDeleteDownloadRoute
  '/api/admin/delete-notification': typeof ApiAdminDeleteNotificationRoute
  '/api/admin/delete-session': typeof ApiAdminDeleteSessionRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/log-notification': typeof ApiAdminLogNotificationRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/mark-notification-read': typeof ApiAdminMarkNotificationReadRoute
  '/api/me/login': typeof ApiMeLoginRoute
  '/api/me/logout': typeof ApiMeLogoutRoute
  '/api/me/stats': typeof ApiMeStatsRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/download-progress': typeof ApiPublicDownloadProgressRoute
  '/api/public/installed': typeof ApiPublicInstalledRoute
  '/api/public/mark-extracted': typeof ApiPublicMarkExtractedRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/installed': typeof InstalledRoute
  '/me': typeof MeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/admin/clear-downloads': typeof ApiAdminClearDownloadsRoute
  '/api/admin/clear-history': typeof ApiAdminClearHistoryRoute
  '/api/admin/clear-notifications': typeof ApiAdminClearNotificationsRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/delete-download': typeof ApiAdminDeleteDownloadRoute
  '/api/admin/delete-notification': typeof ApiAdminDeleteNotificationRoute
  '/api/admin/delete-session': typeof ApiAdminDeleteSessionRoute
  '/api/admin/delete-user': typeof ApiAdminDeleteUserRoute
  '/api/admin/log-notification': typeof ApiAdminLogNotificationRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/mark-notification-read': typeof ApiAdminMarkNotificationReadRoute
  '/api/me/login': typeof ApiMeLoginRoute
  '/api/me/logout': typeof ApiMeLogoutRoute
  '/api/me/stats': typeof ApiMeStatsRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/download-progress': typeof ApiPublicDownloadProgressRoute
  '/api/public/installed': typeof ApiPublicInstalledRoute
  '/api/public/mark-extracted': typeof ApiPublicMarkExtractedRoute
  '/api/public/visit': typeof ApiPublicVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/installed'
    | '/me'
    | '/admin'
    | '/api/admin/clear-downloads'
    | '/api/admin/clear-history'
    | '/api/admin/clear-notifications'
    | '/api/admin/dashboard'
    | '/api/admin/delete-download'
    | '/api/admin/delete-notification'
    | '/api/admin/delete-session'
    | '/api/admin/delete-user'
    | '/api/admin/log-notification'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/mark-notification-read'
    | '/api/me/login'
    | '/api/me/logout'
    | '/api/me/stats'
    | '/api/public/download'
    | '/api/public/download-progress'
    | '/api/public/installed'
    | '/api/public/mark-extracted'
    | '/api/public/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/installed'
    | '/me'
    | '/admin'
    | '/api/admin/clear-downloads'
    | '/api/admin/clear-history'
    | '/api/admin/clear-notifications'
    | '/api/admin/dashboard'
    | '/api/admin/delete-download'
    | '/api/admin/delete-notification'
    | '/api/admin/delete-session'
    | '/api/admin/delete-user'
    | '/api/admin/log-notification'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/mark-notification-read'
    | '/api/me/login'
    | '/api/me/logout'
    | '/api/me/stats'
    | '/api/public/download'
    | '/api/public/download-progress'
    | '/api/public/installed'
    | '/api/public/mark-extracted'
    | '/api/public/visit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/installed'
    | '/me'
    | '/_authenticated/admin'
    | '/api/admin/clear-downloads'
    | '/api/admin/clear-history'
    | '/api/admin/clear-notifications'
    | '/api/admin/dashboard'
    | '/api/admin/delete-download'
    | '/api/admin/delete-notification'
    | '/api/admin/delete-session'
    | '/api/admin/delete-user'
    | '/api/admin/log-notification'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/mark-notification-read'
    | '/api/me/login'
    | '/api/me/logout'
    | '/api/me/stats'
    | '/api/public/download'
    | '/api/public/download-progress'
    | '/api/public/installed'
    | '/api/public/mark-extracted'
    | '/api/public/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstalledRoute: typeof InstalledRoute
  MeRoute: typeof MeRoute
  ApiAdminClearDownloadsRoute: typeof ApiAdminClearDownloadsRoute
  ApiAdminClearHistoryRoute: typeof ApiAdminClearHistoryRoute
  ApiAdminClearNotificationsRoute: typeof ApiAdminClearNotificationsRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminDeleteDownloadRoute: typeof ApiAdminDeleteDownloadRoute
  ApiAdminDeleteNotificationRoute: typeof ApiAdminDeleteNotificationRoute
  ApiAdminDeleteSessionRoute: typeof ApiAdminDeleteSessionRoute
  ApiAdminDeleteUserRoute: typeof ApiAdminDeleteUserRoute
  ApiAdminLogNotificationRoute: typeof ApiAdminLogNotificationRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMarkNotificationReadRoute: typeof ApiAdminMarkNotificationReadRoute
  ApiMeLoginRoute: typeof ApiMeLoginRoute
  ApiMeLogoutRoute: typeof ApiMeLogoutRoute
  ApiMeStatsRoute: typeof ApiMeStatsRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiPublicDownloadProgressRoute: typeof ApiPublicDownloadProgressRoute
  ApiPublicInstalledRoute: typeof ApiPublicInstalledRoute
  ApiPublicMarkExtractedRoute: typeof ApiPublicMarkExtractedRoute
  ApiPublicVisitRoute: typeof ApiPublicVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installed': {
      id: '/installed'
      path: '/installed'
      fullPath: '/installed'
      preLoaderRoute: typeof InstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/visit': {
      id: '/api/public/visit'
      path: '/api/public/visit'
      fullPath: '/api/public/visit'
      preLoaderRoute: typeof ApiPublicVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mark-extracted': {
      id: '/api/public/mark-extracted'
      path: '/api/public/mark-extracted'
      fullPath: '/api/public/mark-extracted'
      preLoaderRoute: typeof ApiPublicMarkExtractedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/installed': {
      id: '/api/public/installed'
      path: '/api/public/installed'
      fullPath: '/api/public/installed'
      preLoaderRoute: typeof ApiPublicInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-progress': {
      id: '/api/public/download-progress'
      path: '/api/public/download-progress'
      fullPath: '/api/public/download-progress'
      preLoaderRoute: typeof ApiPublicDownloadProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/stats': {
      id: '/api/me/stats'
      path: '/api/me/stats'
      fullPath: '/api/me/stats'
      preLoaderRoute: typeof ApiMeStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/logout': {
      id: '/api/me/logout'
      path: '/api/me/logout'
      fullPath: '/api/me/logout'
      preLoaderRoute: typeof ApiMeLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/login': {
      id: '/api/me/login'
      path: '/api/me/login'
      fullPath: '/api/me/login'
      preLoaderRoute: typeof ApiMeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mark-notification-read': {
      id: '/api/admin/mark-notification-read'
      path: '/api/admin/mark-notification-read'
      fullPath: '/api/admin/mark-notification-read'
      preLoaderRoute: typeof ApiAdminMarkNotificationReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/log-notification': {
      id: '/api/admin/log-notification'
      path: '/api/admin/log-notification'
      fullPath: '/api/admin/log-notification'
      preLoaderRoute: typeof ApiAdminLogNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-user': {
      id: '/api/admin/delete-user'
      path: '/api/admin/delete-user'
      fullPath: '/api/admin/delete-user'
      preLoaderRoute: typeof ApiAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-session': {
      id: '/api/admin/delete-session'
      path: '/api/admin/delete-session'
      fullPath: '/api/admin/delete-session'
      preLoaderRoute: typeof ApiAdminDeleteSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-notification': {
      id: '/api/admin/delete-notification'
      path: '/api/admin/delete-notification'
      fullPath: '/api/admin/delete-notification'
      preLoaderRoute: typeof ApiAdminDeleteNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-download': {
      id: '/api/admin/delete-download'
      path: '/api/admin/delete-download'
      fullPath: '/api/admin/delete-download'
      preLoaderRoute: typeof ApiAdminDeleteDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clear-notifications': {
      id: '/api/admin/clear-notifications'
      path: '/api/admin/clear-notifications'
      fullPath: '/api/admin/clear-notifications'
      preLoaderRoute: typeof ApiAdminClearNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clear-history': {
      id: '/api/admin/clear-history'
      path: '/api/admin/clear-history'
      fullPath: '/api/admin/clear-history'
      preLoaderRoute: typeof ApiAdminClearHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clear-downloads': {
      id: '/api/admin/clear-downloads'
      path: '/api/admin/clear-downloads'
      fullPath: '/api/admin/clear-downloads'
      preLoaderRoute: typeof ApiAdminClearDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InstalledRoute: InstalledRoute,
  MeRoute: MeRoute,
  ApiAdminClearDownloadsRoute: ApiAdminClearDownloadsRoute,
  ApiAdminClearHistoryRoute: ApiAdminClearHistoryRoute,
  ApiAdminClearNotificationsRoute: ApiAdminClearNotificationsRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminDeleteDownloadRoute: ApiAdminDeleteDownloadRoute,
  ApiAdminDeleteNotificationRoute: ApiAdminDeleteNotificationRoute,
  ApiAdminDeleteSessionRoute: ApiAdminDeleteSessionRoute,
  ApiAdminDeleteUserRoute: ApiAdminDeleteUserRoute,
  ApiAdminLogNotificationRoute: ApiAdminLogNotificationRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMarkNotificationReadRoute: ApiAdminMarkNotificationReadRoute,
  ApiMeLoginRoute: ApiMeLoginRoute,
  ApiMeLogoutRoute: ApiMeLogoutRoute,
  ApiMeStatsRoute: ApiMeStatsRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiPublicDownloadProgressRoute: ApiPublicDownloadProgressRoute,
  ApiPublicInstalledRoute: ApiPublicInstalledRoute,
  ApiPublicMarkExtractedRoute: ApiPublicMarkExtractedRoute,
  ApiPublicVisitRoute: ApiPublicVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
